config/routes.rb
AdvancedWars::Application.routes.draw do

  resources :pages, only: [:index]

  get 'games/flappy' => 'games#flappy', as: :flappy

  get 'games/testgame' => 'games#testgame', as: :testgame

  get 'pages/about' => 'pages#about', as: :about
  get 'pages/contact' => 'pages#contact', as: :contact

   root 'pages#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def flappy
    @javascript_file = "flappy_isaac"
  end
  def testgame
  	@javascript_file = "testgame"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #this controller serves the pages of the website that are mostly static
  #pass in the name without the extention into @javascript_file and it will
  #be passed to the view to be loaded

  #phaser is loaded already in application.html.erb
  def index

  end

  def about

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def li_active_if condition, link
    # content_tag(:li, link_to("3", users_path))
    if condition
      content_tag(:li, link, :class => 'active')
    else
      content_tag(:li, link)
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def index_active
    params[:controller] == "pages" && params[:action] == "index" ? true : false
  end

  def about_active
    params[:controller] == "pages" && params[:action] == "about" ? true : false
  end

  def contact_active
    params[:controller] == "pages" && params[:action] == "contact" ? true : false
  end
end

app/views/games/flappy.html.erb
<center>
  <h1>
    Flappy Tutorial
  </h1>

  <div id="game_div"></div>
</center>

app/views/games/testgame.html.erb
<center>
  <h1>
    Test Game Tutorial
  </h1>

  <div id="test_game_div"></div>
</center>

app/views/layouts/_dropdown_items.html.erb
<li><%= link_to "Flappy Isaacs", flappy_path %></li>
<li><%= link_to "Test Game", testgame_path %></li>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Steve & Isaac's Site", root_path, :class => "navbar-brand" %>
    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <%= li_active_if index_active, link_to('Home', root_path) %>
        <li><a href="#">Blog</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <%= render 'layouts/dropdown_items' %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= li_active_if about_active, link_to("About", about_path) %>
        <%= li_active_if contact_active, link_to("Contact", contact_path) %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AdvancedWarsPrototype</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <% if params[:controller] == "games" %>
      <%= javascript_include_tag "phaser.min.js"%>
      <%= javascript_include_tag @javascript_file if !@javascript_file.nil? %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body style class>
<div class="container">
  <%= render 'layouts/header' %>
  <div class="page-header"></div>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
About

app/views/pages/contact.html.erb
Contact